version: "3.9"
services:
  backend:
    build: ./backend
    container_name: brainmash-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: always

  frontend:
    build: ./frontend
    container_name: brainmash-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    restart: always
